# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sloctl < Formula
  desc "Command-line client for Nobl9"
  homepage "https://docs.nobl9.com/sloctl-user-guide"
  version "0.0.97"

  on_macos do
    url "https://github.com/nobl9/sloctl/releases/download/v0.0.97/sloctl-macos-0.0.97"
    sha256 "0623e74b5cb74048644f8d5b2907ca9f854ae7a4c03c3b5c5fe482891618c5e9"

    def install
      bin.install Dir['sloctl-*-0.0.97'].first()  => "sloctl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Sloctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nobl9/sloctl/releases/download/v0.0.97/sloctl-linux-0.0.97"
      sha256 "d070ef6292bcfa24bff7b601fb8f1ea8b8cf023b440f89d903cf05dcb7358d32"

      def install
        bin.install Dir['sloctl-*-0.0.97'].first()  => "sloctl"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the command-line client for Nobl9!

      To see help and a list of available commands type:
        $ sloctl help

      For more information on how to use the command-line client
      and the Nobl9 managed cloud service, visit:
        https://docs.nobl9.com/sloctl-user-guide
    EOS
  end

  test do
    assert_predicate bin/"sloctl", :exist?
    system "sloctl", "--help"
  end
end
