# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sloctl < Formula
  desc "Command-line client for Nobl9"
  homepage "https://docs.nobl9.com/sloctl-user-guide"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nobl9/sloctl/releases/download/v0.11.0/sloctl-0.11.0-darwin-amd64"
      sha256 "2de444f62121a0053326d4febc084f1f6951ad2ba77ba242598f5f955f47a028"

      def install
        bin.install Dir['sloctl-*-0.11.0'].first()  => "sloctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nobl9/sloctl/releases/download/v0.11.0/sloctl-0.11.0-darwin-arm64"
      sha256 "65dfa70e900e7595764821e56cff13aaaa4904d72e59ccc75823c3504f586f0e"

      def install
        bin.install Dir['sloctl-*-0.11.0'].first()  => "sloctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nobl9/sloctl/releases/download/v0.11.0/sloctl-0.11.0-linux-amd64"
        sha256 "aa59bb0ebdb24b779e7b1f41f82a45b38b774a78afc31b039e22b46f8b03c7c6"

        def install
          bin.install Dir['sloctl-*-0.11.0'].first()  => "sloctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nobl9/sloctl/releases/download/v0.11.0/sloctl-0.11.0-linux-arm64"
        sha256 "1506ed5a08487927f455ddbec7565a3b3d7aab2f0d169e99c1bb5378a12c1077"

        def install
          bin.install Dir['sloctl-*-0.11.0'].first()  => "sloctl"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the command-line client for Nobl9!

      To see help and a list of available commands type:
        $ sloctl help

      For more information on how to use the command-line client
      and the Nobl9 managed cloud service, visit:
        https://docs.nobl9.com/sloctl-user-guide
    EOS
  end

  test do
    assert_predicate bin/"sloctl", :exist?
    system "sloctl", "--help"
  end
end
