# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sloctl < Formula
  desc "Command-line client for Nobl9"
  homepage "https://nobl9.com"
  version "0.0.86"

  on_macos do
    url "https://github.com/nobl9/sloctl/releases/download/v0.0.86/sloctl-macos-0.0.86"
    sha256 "7ac87c36fd2643a509837869423db0ea3d961acbbe801e7eecf2beac052a4043"

    def install
      bin.install Dir['sloctl-*-0.0.86'].first()  => "sloctl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Sloctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nobl9/sloctl/releases/download/v0.0.86/sloctl-linux-0.0.86"
      sha256 "27a4064a7c6cf8509cad3421722584e17d11ddfbb47997a6ebe46c0d6f6db863"

      def install
        bin.install Dir['sloctl-*-0.0.86'].first()  => "sloctl"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing the command-line client for Nobl9!

      To see help and a list of available commands type:
        $ sloctl help

      For more information on how to use the command-line client
      and the Nobl9 managed cloud service, visit:
        https://nobl9.com
    EOS
  end

  test do
    assert_predicate bin/"sloctl", :exist?
    system "sloctl", "--help"
  end
end
